Racing2
nahyun0423/java-racingcar pull request #2
Opened 2024-03-22 08:14 UTC by nahyun0423

2024-03-28 00:19 UTC, kakao-gray-great requested changes
수고하셨습니다 나현님~
확실히 많이 늘었네요 ^^

근데 테스트 코드는 여전히 부족한 것 같아요.
TDD로 작성하는게 목표였는데, TDD를 고민한 흔적이 보이지 않는 것 같습니다.
실제 경주에 대한 테스트가 없어서 어떤 식으로 경기의 승패가 나는지 판단하기 어려운 것 같아요.
추가하면 더 좋은 코드가 될 것 같습니다.

리뷰 확인하고 대댓글 남겨주세요~~

2024-03-28 00:19 UTC, kakao-gray-great commented on src/main/java/CountTry.java
> +    }
이렇게 함으로써 다른 로직에서 굳이 검증을 안해줘도 되겠네요 👍

2024-03-28 00:19 UTC, kakao-gray-great commented on src/main/java/Entry.java
> +public class Entry {
entry 라는 객체명은 무슨 뜻인가요?
어떤 의미에서 지었는지 궁금합니다

2024-03-28 00:19 UTC, kakao-gray-great commented on src/main/java/Car.java
>      }
현재 구조는 위치와 이름이 모두 같아야 동일한 객체로 인정이 되겠네요!
추가로 고민을 해보면 좋을 것 같아요.
1번 위치에 계시는 나현님과 3번 위치에 계시는 나현님은 서로 다른 나현님일까요?

2024-03-28 00:19 UTC, kakao-gray-great commented on src/main/java/Cars.java
>  public class Cars {
일급 컬렉션 👍
근데 중복 검증, 비어있는 값 검증 등 일급 컬렉션을 활용해서 더 많은 것들을 해볼 수 있을 것 같아요.

2024-03-28 00:19 UTC, kakao-gray-great commented on src/main/java/Game.java
> +    private InputView inputView = new InputView();
view 객체를 생성한 이유가 무엇인가요?

2024-03-28 00:19 UTC, kakao-gray-great commented on src/main/java/Input.java
>  }
InputView와 Input의 역할이 겹치는 것 같은데, 한번 고민해봐주시면 좋을 것 같아요.

2024-03-28 00:19 UTC, kakao-gray-great commented on src/main/java/Judge.java
> +    private int maxPosition = 0;
maxPosition이라는 변수명이 올바르지 않지 않을까 싶어요.
maxPosition = 0 이라고 되어 있어서 사람들이 오해할 수 있을 것 같네요.

2024-03-28 00:19 UTC, kakao-gray-great commented on src/main/java/Judge.java
> +public class Judge {
굳이 이 클래스가 필요할까 싶네요.
일급 컬렉션을 사용했다면 Cars 자체에서 최대 값을 뽑아내기가 쉽지 않을까 생각이 듭니다.

2024-03-28 00:19 UTC, kakao-gray-great commented on src/main/java/Name.java
> +            throw new RuntimeException("이름은 1~5글자이어야 합니다.");
RuntimeException 보다 더 구체화된 예외를 던져주는게 좋을 것 같아요.

2024-03-31 09:22 UTC, nahyun0423 commented on src/main/java/Entry.java
> +public class Entry {
참가자라는 의미로 지은 것입니다. 더 자세하게는 참가한 자동차에 대한 객체명입니다.

2024-03-31 09:22 UTC, nahyun0423 commented on src/main/java/Game.java
> +    private InputView inputView = new InputView();
view의 메소드는 Game 클래스에서만 사용하니까 static을 붙이는 게 더 비효율적이라고 생각했는데, 아닌가요?

2024-03-31 09:22 UTC, nahyun0423 commented on src/main/java/Input.java
>  }
넵 input클래스의 로직을 inputView에 넣어서 합치고 input클래스는 지웠습니다.

2024-03-31 09:22 UTC, nahyun0423 commented on src/main/java/Judge.java
> +    private int maxPosition = 0;
최대 position값을 저장해둔다는 의미의 변수명으로 maxPositionStorage로 수정했습니다.

2024-03-31 09:22 UTC, nahyun0423 commented on src/main/java/Name.java
> +            throw new RuntimeException("이름은 1~5글자이어야 합니다.");
IllegalArgumentException 으로 수정했습니다.

2024-03-31 09:22 UTC, nahyun0423 commented on src/main/java/Car.java
>      }
그럼 위치를 생성자에 포함하면 안된다는 말인가요 ,,,?

2024-03-31 09:29 UTC, kakao-gray-great requested changes

2024-03-31 09:29 UTC, kakao-gray-great commented on src/main/java/Car.java
>      }
아니요
이름만 같아도 동일한 객체로 인정되게 만들면 되지 않을까요?

2024-03-31 09:29 UTC, kakao-gray-great commented on src/main/java/Entry.java
> +public class Entry {
그럼 자동차 객체가 있고, 참가한 자동차 객체가 있다는 건데 좋지 않은 구조인 것 같아요.
추가로 참가한 자동차 객체인데 행동이 split하고 removeGap을 하는 것도 맞지 않는 것 같네요.

2024-03-31 09:29 UTC, kakao-gray-great commented on src/main/java/Game.java
> +    private InputView inputView = new InputView();
어떤 면에서 비효율적인지 조금 더 설명 가능할까요?

2024-04-02 07:09 UTC, nahyun0423 commented on src/main/java/Game.java
> +    private InputView inputView = new InputView();
static은 매번 인스턴스를 생성하며 낭비되는 메모리를 줄일 수 있어 여러 클래스에서 인스턴스를 생성해야할 때 사용하면 좋지만, 지금은 view의 메소드를 이용하는 곳이 Game 클래스뿐이니 객체를 생성하는 게 더 효율적이라고 생각했습니다.

2024-04-02 07:09 UTC, nahyun0423 commented on src/main/java/Entry.java
> +public class Entry {
CarGenerater로 클래스 이름을 변경했습니다.

2024-04-02 07:09 UTC, nahyun0423 commented on src/main/java/Judge.java
> +public class Judge {
Cars에 로직 합쳤습니다.

2024-04-02 07:09 UTC, nahyun0423 commented on src/main/java/Car.java
>      }
Car에 equals 오버라이드해서 이름만 같아도 동일한 객체로 인정되게 만들었습니다.

2024-04-02 07:36 UTC, kakao-gray-great commented on src/main/java/Game.java
> +    private InputView inputView = new InputView();
객체를 생성하는 것과 static을 사용하는 것의 메모리가 어떻게 달라지나요?

2024-04-02 07:50 UTC, nahyun0423 commented on src/main/java/Game.java
> +    private InputView inputView = new InputView();
new 연산자로 객체를 생성하면 여러 개를 생성했을 때 각각 독립적으로 메모리에 할당이 되지만, static은 static 영역에 메모리가 할당되어 어디서 객체를 사용하든 같은 객체에 접근하여 같은 값을 사용하게 됩니다.

2024-04-03 00:19 UTC, kakao-gray-great commented on src/main/java/Game.java
> +    private InputView inputView = new InputView();
new 연산을 사용하는 것보다 static 을 사용하는게 메모리 비용이 크나요?

2024-04-06 05:55 UTC, nahyun0423 commented on src/main/java/Game.java
> +    private InputView inputView = new InputView();
여러 곳에서 사용한다면 static의 메모리 비용이 더 적겠지만 지금은 한 곳에서만 사용하니 new 연산을 사용하는 게 메모리 비용이 더 적습니다.

2024-04-13 06:48 UTC, merged